Repository react-bootstrap/react-bootstrap, pull requests merged in 2019-10, with the labels that each got.

#4604 ci(actions): fix build not triggering on forked prs
  .github/workflows/nodejs.yml
Labels: bug

#4597 Fix(Bs3): Remove unsafe lifecycles by upgrading uncontrollable to ^7.0.2
  package.json
  src/Dropdown.js
  src/Navbar.js
  src/Panel.js
  src/PanelGroup.js
  src/TabContainer.js
  src/Tabs.js
  src/ToggleButtonGroup.js
  src/utils/bootstrapUtils.js
  test/DropdownButtonSpec.js
  test/DropdownSpec.js
  test/NavbarSpec.js
  test/PanelGroupSpec.js
  test/PanelSpec.js
  test/TabsSpec.js
  yarn.lock
Labels: Bootstrap 3

#4696 docs: List.Item to ListGroup.Item
  www/src/pages/components/list-group.mdx
Labels: bug, docs

#4665 Add About section to the website
  www/src/components/SideNav.js
  www/src/pages/about.mdx
Labels: docs, enhancement

#4435 fix(FormControl): onChange and innerRef ts decls (#3583,#3568,#2781)
  types/components/FormControl.d.ts
  types/simple.test.tsx
Labels: types

#4703 docs(Navs): mentions that vertical navs styled as tabs are unsupported by Bootstrap
  www/src/pages/components/navs.mdx
Labels: docs, enhancement
