Repository react-bootstrap/react-bootstrap, pull requests merged in 2019-08, with the labels that each got.

#4246 fix(types): Toast component
  types/components/Toast.d.ts
  types/simple.test.tsx
Labels: types

#4244 Remove lifecycle warnings for v3
  src/Carousel.js
  src/CarouselItem.js
  src/Dropdown.js
  src/TabContent.js
  src/utils/deprecationWarning.js
Labels: Bootstrap 3

#4228 feat(types): add useAccordionToggle types
  src/AccordionToggle.js
  src/index.js
  src/useAccordionToggle.js
  types/components/AccordionToggle.d.ts
  types/components/index.d.ts
  www/src/pages/components/accordion.mdx
Labels: enhancement, types

#4375 Drops @react-bootstrap/react-popper
  package.json
  yarn.lock
Labels: dependencies

#4362 Update ResponsiveEmbed example
  www/src/examples/ResponsiveEmbed.js
Labels: bug, docs
