Repository react-bootstrap/react-bootstrap, pull requests merged in 2019-07, with the labels that each got.

#3992 Refactor Row to use forwardRef
  src/Row.js
Labels: enhancement

#3982 Migrate doc examples to functional components
  www/src/components/ReactPlayground.js
  www/src/examples/.eslintrc
  www/src/examples/Alert/Dismissible.js
  www/src/examples/Alert/DismissibleControlled.js
  www/src/examples/Button/Loading.js
  www/src/examples/Button/ToggleButtonGroupControlled.js
  www/src/examples/Carousel/Controlled.js
  www/src/examples/Collapse.js
  www/src/examples/Fade.js
  www/src/examples/Form/ValidationNative.js
  www/src/examples/Modal/Basic.js
  www/src/examples/Modal/CustomSizing.js
  www/src/examples/Modal/DefaultSizing.js
  www/src/examples/Modal/Grid.js
  www/src/examples/Modal/VerticallyCentered.js
  www/src/examples/Nav/Dropdown.js
  www/src/examples/Overlays/Overlay.js
  www/src/examples/Overlays/PopoverContained.js
  www/src/examples/Overlays/ScheduleUpdate.js
  www/src/examples/Overlays/TooltipOverlay.js
  www/src/examples/Tabs/Controlled.js
  www/src/examples/Toast/Autohide.js
  www/src/examples/Toast/Dismissible.js
Labels: docs

#3974 Bootstrap 3: Bump Dependencies
  CHANGELOG.md
  package.json
  yarn.lock
Labels: Bootstrap 3

#4103 feat: Add simple Popover type test
  types/simple.test.tsx
Labels: types
